name: Java CI with Gradle

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Export Libs
        run: ./gradlew copyToLib
      - name: Download Proguard
        run: wget https://github.com/Guardsquare/proguard/releases/download/v7.2.0/proguard-7.2.0.tar.gz -O proguard.tar.gz && tar -xzf proguard.tar.gz && rm proguard.tar.gz
      - name: Download Proguard config
        run: wget https://evie.pw/api/getProGuardConf?key=evielikestobepat -O proguard.cfg
      - name: Run Proguard
        run: ./proguard-7.2.0/bin/proguard.sh @proguard.cfg
      - name: Archive Build
        uses: actions/upload-artifact@v2
        with:
          name: archive-build
          path: build/libs
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'
      - id: 'upload-jar'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'build/libs/EvieClient-1.0.0.jar'
          destination: 'teamevieclient.appspot.com/1.8/'
