name: Java CI with Gradle

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Leave a ci note
        run: 'echo "$(git rev-parse --short HEAD)" > src/main/resources/ci.txt'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive Build
        uses: actions/upload-artifact@v2
        with:
          name: archive-build
          path: build/libs/EvieClient-1.0.0_obf.jar
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.gcp_credentials }}"
      - id: "upload-jar"
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: "build/libs/EvieClient-1.0.0_obf.jar"
          destination: "teamevieclient.appspot.com/1.8/"
